# Generated by Django 5.0.5 on 2024-06-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estd_formacion', models.CharField(max_length=100)),
                ('estd_meta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metas_formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metd_modalidad', models.CharField(max_length=100)),
                ('metf_formacion', models.CharField(max_length=100)),
                ('metf_meta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metas_poblacion_vulnerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metpv_poblacion', models.CharField(max_length=100)),
                ('metpv_tipo_poblacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='P04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_p04', models.DateField()),
                ('codigo_regional', models.CharField(max_length=150)),
                ('nombre_regional', models.CharField(max_length=150)),
                ('codigo_centro', models.CharField(max_length=150)),
                ('nombre_centro', models.CharField(max_length=150)),
                ('identificador_ficha', models.CharField(max_length=150)),
                ('estado_curso', models.CharField(max_length=150)),
                ('codigo_nivel_formacion', models.CharField(max_length=150)),
                ('nivel_formacion', models.CharField(max_length=150)),
                ('codigo_jornada', models.CharField(max_length=150)),
                ('nombre_jornada', models.CharField(max_length=150)),
                ('tipo_de_formacion', models.CharField(max_length=150)),
                ('fecha_inicio_ficha', models.DateField()),
                ('fecha_terminacion_ficha', models.DateField()),
                ('etapa_ficha', models.CharField(max_length=150)),
                ('modalidad_formacion', models.CharField(max_length=150)),
                ('codigo_sector_programa', models.CharField(max_length=150)),
                ('nombre_sector_programa', models.CharField(max_length=150)),
                ('codigo_ocupacion', models.CharField(max_length=150)),
                ('nombre_ocupacion', models.CharField(max_length=150)),
                ('codigo_programa', models.CharField(max_length=150)),
                ('version_programa', models.CharField(max_length=150)),
                ('nombre_programa_formacion', models.CharField(max_length=150)),
                ('red', models.CharField(max_length=150)),
                ('codigo_pais_curso', models.CharField(max_length=150)),
                ('nombre_pais_curso', models.CharField(max_length=150)),
                ('codigo_departamento_curso', models.CharField(max_length=150)),
                ('nombre_departamento_curso', models.CharField(max_length=150)),
                ('codigo_municipio_curso', models.CharField(max_length=150)),
                ('nombre_municipio_curso', models.CharField(max_length=150)),
                ('codigo_convenio', models.CharField(max_length=150)),
                ('nombre_convenio', models.CharField(max_length=150)),
                ('ampliacion_covetura', models.CharField(max_length=150)),
                ('codigo_programa_especial', models.CharField(max_length=150)),
                ('nombre_programa_espcial', models.CharField(max_length=150)),
                ('numero_curso', models.CharField(max_length=150)),
                ('total_aprendices_masculinos', models.CharField(max_length=150)),
                ('total_aprendices_femeninos', models.CharField(max_length=150)),
                ('total_aprendices_nobinario', models.CharField(max_length=150)),
                ('total_aprendices', models.CharField(max_length=150)),
                ('total_aprendices_activos', models.CharField(max_length=150)),
                ('duracion_programa', models.CharField(max_length=150)),
                ('nombre_nuevo_sector', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_poblacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=100)),
                ('rol_descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_nombre', models.CharField(max_length=100)),
                ('est_modalidad', models.CharField(max_length=100)),
                ('est_total_meta', models.CharField(max_length=100)),
                ('estrategia_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estrategia_detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('per_documento', models.AutoField(primary_key=True, serialize=False)),
                ('per_tipo_documento', models.CharField(max_length=100)),
                ('per_correo', models.EmailField(max_length=254, unique=True)),
                ('per_nombres', models.CharField(max_length=60)),
                ('per_apellidos', models.CharField(max_length=60)),
                ('per_telefono', models.CharField(max_length=10)),
                ('p04', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.p04')),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poblacion')),
                ('rol', models.ManyToManyField(to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met_centro_formacion', models.CharField(max_length=150)),
                ('met_codigo', models.CharField(max_length=150)),
                ('met_fecha_inicio', models.DateField()),
                ('met_fecha_fin', models.DateField()),
                ('met_año', models.CharField(max_length=4)),
                ('met_total_otras_poblaciones', models.CharField(max_length=100)),
                ('met_total_victimas', models.CharField(max_length=100)),
                ('met_total_hechos_victimizantes', models.CharField(max_length=100)),
                ('met_total_desplazados_violencia', models.CharField(max_length=100)),
                ('met_total_titulada', models.CharField(max_length=100)),
                ('met_total_complementaria', models.CharField(max_length=100)),
                ('met_total_poblacion_vulnerable', models.CharField(max_length=100)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estrategia')),
                ('metas_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metas_formacion')),
                ('metas_poblacion_vulnerable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metas_poblacion_vulnerable')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
