# Generated by Django 5.0.5 on 2024-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ALMAGUER', 'Almaguer'), ('ARGELIA', 'Argelia'), ('BALBOA', 'Balboa'), ('BOLÍVAR', 'Bolívar'), ('BUENOS AIRES', 'Buenos Aires'), ('CAJIBIO', 'Cajibío'), ('CALDONO', 'Caldono'), ('CALOTO', 'Caloto'), ('CORINTO', 'Corinto'), ('EL TAMBO', 'El Tambo'), ('FLORENCIA', 'Florencia'), ('GUACHENÉ', 'Guachené'), ('GUAPI', 'Guapi'), ('INZA', 'Inza'), ('JAMBALO', 'Jambaló'), ('LA SIERRA', 'La Sierra'), ('LA VEGA', 'La Vega'), ('LOPEZ', 'López'), ('MERCADERES', 'Mercaderes'), ('MIRANDA', 'Miranda'), ('MORALES', 'Morales'), ('PATIA (EL BORDO)', 'Patía (El Bordo)'), ('PAEZ (BELALCAZAR)', 'Páez (Belalcázar)'), ('POPAYÁN', 'Popayán'), ('PUERTO TEJADA', 'Puerto Tejada'), ('PURACÉ (COCONUCO)', 'Puracé (Coconuco)'), ('SAN SEBASTIÁN', 'San Sebastián'), ('SANTANDER DE QUILICHAO', 'Santander de Quilichao'), ('SANTA ROSA', 'Santa Rosa'), ('SILVIA', 'Silvia'), ('SOTARA (PAISPAMBA)', 'Sotará (Paispamba)'), ('SUCRE', 'Sucre'), ('SUAREZ', 'Suarez'), ('TIMBIO', 'Timbío'), ('TIMBIQUI', 'Timbiquí'), ('TOTORO', 'Totoró'), ('VILLA RICA', 'Villa Rica')], max_length=150)),
            ],
        ),
    ]
