# Generated by Django 5.0.5 on 2024-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilinguismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bilinguismo', models.CharField(choices=[('ENGLISH DOES WORK - LEVEL 1', 'English does work - level 1'), ('ENGLISH DOES WORK - LEVEL 5', 'English does work - level 5'), ('ENGLISH DOES WORK - LEVEL 6', 'English does work - level 6'), ('INGLES BASICO - NIVEL 1', 'Ingles basico nivel 1'), ('INGLES BASICO - NIVEL 3', 'Ingles basico nivel 3'), ('INGLES BASICO - NIVEL 4', 'Ingles basico nivel 4')], max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(choices=[('ALMAGUER', 'Almaguer'), ('ARGELIA', 'Argelia'), ('BALBOA', 'Balboa'), ('BOLÍVAR', 'Bolívar'), ('BUENOS AIRES', 'Buenos Aires'), ('CAJIBIO', 'Cajibío'), ('CALDONO', 'Caldono'), ('CALOTO', 'Caloto'), ('CORINTO', 'Corinto'), ('EL TAMBO', 'El Tambo'), ('FLORENCIA', 'Florencia'), ('GUACHENÉ', 'Guachené'), ('GUAPI', 'Guapi'), ('INZA', 'Inza'), ('JAMBALO', 'Jambaló'), ('LA SIERRA', 'La Sierra'), ('LA VEGA', 'La Vega'), ('LOPEZ', 'López'), ('MERCADERES', 'Mercaderes'), ('MIRANDA', 'Miranda'), ('MORALES', 'Morales'), ('PATIA (EL BORDO)', 'Patía (El Bordo)'), ('PAEZ (BELALCAZAR)', 'Páez (Belalcázar)'), ('PIENDAMÓ', 'Piendamó'), ('PIAMONTE', 'Piamonte'), ('POPAYÁN', 'Popayán'), ('ROSAS', 'Rosas'), ('PUERTO TEJADA', 'Puerto Tejada'), ('PURACÉ (COCONUCO)', 'Puracé (Coconuco)'), ('SAN SEBASTIÁN', 'San Sebastián'), ('SANTANDER DE QUILICHAO', 'Santander de Quilichao'), ('SANTA ROSA', 'Santa Rosa'), ('SILVIA', 'Silvia'), ('SOTARA (PAISPAMBA)', 'Sotará (Paispamba)'), ('SUCRE', 'Sucre'), ('SUAREZ', 'Suarez'), ('TIMBIO', 'Timbío'), ('TORIBIO', 'Toribio'), ('TIMBIQUI', 'Timbiquí'), ('TOTORO', 'Totoró'), ('VILLA RICA', 'Villa Rica')], max_length=150),
        ),
    ]
