# Generated by Django 5.0.5 on 2024-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_formacion', models.CharField(choices=[('AUXILIAR', 'Auxiliar'), ('CURSO ESPECIAL', 'Curso especial'), ('EVENTO', 'Evento'), ('OPERARIO', 'Operario'), ('TÉCNICO', 'Técnico'), ('TECNÓLOGO', 'Tecnólogo')], max_length=150)),
            ],
        ),
    ]
