# Generated by Django 5.0.5 on 2024-09-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilinguismo_programa',
            fields=[
                ('bil_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('bil_version', models.CharField(max_length=150)),
                ('Bil_programa', models.CharField(max_length=200)),
                ('bil_duracion', models.CharField(max_length=150)),
                ('bil_modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.modalidad')),
            ],
        ),
    ]
