# Generated by Django 5.0.5 on 2024-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bilinguismo_alter_municipio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_formacion',
            name='nivel_formacion',
            field=models.CharField(choices=[('AUXILIAR', 'Auxiliar'), ('CURSO ESPECIAL', 'Curso especial'), ('EVENTO', 'Evento'), ('OPERARIO', 'Operario'), ('TÉCNICO', 'Técnico'), ('TECNÓLOGO', 'Tecnólogo'), ('PROFUNDIZACION', 'Profundizacion'), ('BILINGUISMO', 'Bilinguismo'), ('SIN BILINGUISMO', 'Sin_bilinguismo')], max_length=150),
        ),
    ]
