# Generated by Django 5.0.5 on 2024-09-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bilinguismo_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_de_formacion',
            name='centro_de_formacion',
            field=models.CharField(max_length=150),
        ),
    ]
