# Generated by Django 5.0.5 on 2024-09-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_regional_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_formacion',
            name='nivel_formacion',
            field=models.CharField(max_length=150),
        ),
    ]
