# Generated by Django 5.0.5 on 2024-07-25 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('pobl_id', models.AutoField(primary_key=True, serialize=False)),
                ('pobl_fecha_poblacion', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('indigenas_cupos_meta', models.IntegerField()),
                ('indigenas_aprendices_meta', models.IntegerField()),
                ('inpec_cupos_meta', models.IntegerField()),
                ('inpec_aprendices_meta', models.IntegerField()),
                ('jovenes_cupos_meta', models.IntegerField()),
                ('jovenes_aprendices_meta', models.IntegerField()),
                ('adolescente_cupos_meta', models.IntegerField()),
                ('adolescente_aprendices_meta', models.IntegerField()),
                ('mujer_cupos_meta', models.IntegerField()),
                ('mujer_aprendices_meta', models.IntegerField()),
                ('indigenas_cupos_ejecucion', models.IntegerField()),
                ('indigenas_aprendices_ejecucion', models.IntegerField()),
                ('inpec_cupos_ejecucion', models.IntegerField()),
                ('inpec_aprendices_ejecucion', models.IntegerField()),
                ('jovenes_cupos_ejecucion', models.IntegerField()),
                ('jovenes_aprendices_ejecucion', models.IntegerField()),
                ('adolescente_cupos_ejecucion', models.IntegerField()),
                ('adolescente_aprendices_ejecucion', models.IntegerField()),
                ('mujer_cupos_ejecucion', models.IntegerField()),
                ('mujer_aprendices_ejecucion', models.IntegerField()),
                ('per_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
