# Generated by Django 5.0.5 on 2024-09-11 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia_detalle',
            name='estd_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.meta'),
        ),
    ]
