# Generated by Django 5.0.5 on 2024-09-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_estrategia_detalle_estd_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrategia',
            name='est_total_meta',
        ),
        migrations.RemoveField(
            model_name='estrategia',
            name='met_id',
        ),
    ]
