# Generated by Django 5.0.5 on 2024-07-31 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_datos_vulnerables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento_vulnerables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicadores', models.CharField(max_length=250)),
                ('grupo', models.CharField(max_length=250)),
                ('meta_2024', models.CharField(max_length=150)),
                ('ejecucion', models.CharField(max_length=150)),
                ('porcentaje_ejecucion', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('per_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
